version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: spanish_tutor_user
      POSTGRES_PASSWORD: spanish_tutor_pass
      POSTGRES_DB: spanish_tutor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: